package yong.chul.coupon.issued_coupon_app.usecase.exception

class DuplicateCouponException: RuntimeException("중복 발급 되었습니다.") {
}